# This file is a part of template-python. Manual changes will be overwritten.

name: PR title validation

on:
  push:
    branches:
      - develop
      - release**
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]

jobs:
  pr-sanity:
    runs-on: ubuntu-22.04

    steps:
      - uses: emedgene/ga.emedgene.pull-request-action@main
        if: github.event_name == 'pull_request'
        with:
          prTitle : ${{ github.event.pull_request.title }}
      - uses: emedgene/ga.emedgene.pull-request-action@main
        if: github.event_name == 'push'
        with:
          prTitle : ${{ github.event.head_commit.message }}
